version: '3'

services:
    app:
        depends_on:
            - mysql

    mysql:
        build:
            context: ./docker/db
            dockerfile: Dockerfile.mysql
        volumes:
            - ./.data/mysql:/var/lib/mysql:rw
        env_file:
            - .env
        ports:
            - "3306:3306"
