snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_URL)%"
        doctrine:
            type: predis
            alias: doctrine
            dsn: '%env(REDIS_DSN)%'
        session:
            type: predis
            alias: session
            dsn: '%env(REDIS_DSN)%'
    session:
        client: session
        ttl: 1200
    doctrine:
        metadata_cache:
            client: doctrine
            entity_manager: default
            document_manager: default
        result_cache:
            client: doctrine
            entity_manager: default
        query_cache:
            client: doctrine
            entity_manager: default
